name: Build and Deploy

on:
  push:
    branches:
      - main
    paths:
      - 'edgeone-getip/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24' # 选择适合的 Node.js 版本
      
      - name: Install dependencies
        run: npm install -g edgeone
      - name: Deploy to EdgeOne Pages
        run: cd edgeone-getip && npx edgeone pages deploy -n edgeone-getip -t ${{ secrets.EDGEONE_API_TOKEN }}
        env:
          EDGEONE_API_TOKEN: ${{ secrets.EDGEONE_API_TOKEN }}